security:
  oauth2:
    resource:
      preferTokenInfo: false
      userInfoUri: http://localhost:8080/aac/basicprofile/me
    client:
      clientId: 
      clientSecret: 
      userAuthorizationUri: http://localhost:8080/aac/eauth/authorize
      authenticationScheme: header
      tokenName: oauth_token
      scope: profile.basicprofile.me, user.roles.me
      accessTokenUri: http://localhost:8080/aac/oauth/token
      clientAuthenticationScheme: form  
      preEstablishedRedirectUri: http://localhost:18000/gamification/login/aac
      useCurrentUri: false   

oauth:
  serverUrl: http://localhost:8080/aac
  context: COMPONENTS/GAMIFICATION
  role: ROLE_PROVIDER
    
management:
  context-path: /manage
  port: 9000
  security.enabled: false
  
server:
    port: 18000
    servlet:
      context-path: /gamification
    singeLogoutUrl: http://localhost:18000/gamification/singleLogout
    
spring:
  main:
    allow-bean-definition-overriding: true