security:
  oauth2:
    resource:
      preferTokenInfo: false
      userInfoUri: http://localhost:8080/aac/basicprofile/me
    client:
      clientId: 
      clientSecret: 
      userAuthorizationUri: http://localhost:8080/aac/eauth/authorize
      authenticationScheme: header
      tokenName: oauth_token
      scope: profile.basicprofile.me, user.roles.me
      accessTokenUri: http://localhost:8080/aac/oauth/token
      clientAuthenticationScheme: form  
      preEstablishedRedirectUri: http://localhost:18000/gamification/login/aac
      useCurrentUri: false   

oauth:
  serverUrl: http://localhost:8080/aac
  context: COMPONENTS/GAMIFICATION
  role: ROLE_PROVIDER
    
management:
  endpoints:
      web:
          base-path: ${MANAGEMENT_CONTEXT:/manage}
  server:
      port: ${MANAGEMENT_PORT:9000}
  
server:
    port: ${SERVER_PORT:8010}
    servlet:
      context-path: ${SERVER_CONTEXTPATH:/gamification}
    singeLogoutUrl: http://localhost:18000/gamification/singleLogout
    
spring:
  main:
    allow-bean-definition-overriding: true
    
#
# Platform security
#
#Parent Space
aac:
  roles:
    context: ${AAC_ROLES_CONTEXT:COMPONENTS/GAMIFICATION}
    role: ${AAC_ROLES_ROLE:ROLE_PROVIDER}
  url: ${AAC.URL:http://localhost:8080/aac}
  clientId: ${AAC_CLIENTID:}
  clientSecret: ${AAC_CLIENTSECRET:}

#
# JMX REMOTE CONFIGS
#
com:
  sun:
    management:
      jmxremote:
        port: ${MANAGEMENT_JMXREMOTE_PORT:7777}
        rmi:
          port: ${MANAGEMENT_JMXREMOTE_RMI_PORT:7777}
        authenticate: ${MANAGEMENT_JMXREMOTE_AUTHENTICATE:false}
        ssl: ${MANAGEMENT_JMXREMOTE_SSL:false}
        local:
          only: ${MANAGEMENT_JMXREMOTE_LOCAL_ONLY:false}

java:
  rmi:
    server:
      hostname: localhost